### ISSUE TITLE
input_field maxlength ignored even when value specifically set

### ISSUE THREAD

**Issue by bdmac** [heartcombo/simple_form#1096]
I'm pretty sure this used to work in an older version of simple_form.

We have a form where we are using the following:

``` ruby
= f.input_field :guest_message, as: :text, placeholder: 'Blah blah.', class: 'input-xlarge', maxlength: 140, rows: 4
```

At some point simple_form began dropping the maxlength HTML attribute from the output HTML.  I was unable to pinpoint when exactly this started happening.

I traced the problem down to https://github.com/plataformatec/simple_form/blob/master/lib/simple_form/form_builder.rb#L135

The maxlength attribute is included in the list of ATTRIBUTE_COMPONENTS that are stripped from input_html.  With this setup, it seems that simple_form requires that the wrapper has to be configured with either `b.optional :maxlength` or `b.use :maxlength`.  The default bootstrap configuration does not include `:maxlength` at all though so maxlength is just totally ignored even though it is a valid HTML attribute.

It seems a bit strange and hard to track down the cause of this given that I could add `foo: 'bar'` to my `input_field` and have that show up as an HTML attribute just fine.  Heck I was even able to "fool" simple_form into doing what I wanted by using `maxLength: 140` instead (note the capital L).

Ultimately I was able to get things working by modifying the bootstrap config to allow maxlength by adding `b.optional :maxlength` where appropriate.

Two things come to mind.
1. It does not seem like simple_form should be stripping valid HTML attributes in this fashion.  To me at least that is not expected behavior.
2. At the very least it seems like :maxlength should be included in the bootstrap config since it is in both the base config and in the foundation version.  This would at least prevent this surprise behavior (even though the underlying issue would remain).

**Comment by thehappycoder** [comment]
Is this fix in 3.1.0? I upgraded from 3.0.0 to 3.1.0 and maxlength is gone for me.
