### ISSUE TITLE
Rails 4.2 compatibility

### ISSUE THREAD

**Issue by jamilabreu** [heartcombo/simple_form#1123]
Getting the following on Rails 4.2 beta clean install:
`/gems/inherited_resources-1.4.1/lib/inherited_resources/responder.rb:2:in '<module:InheritedResources>': cannot load such file -- action_controller/metal/responder (LoadError)`

**Comment by abhayn-webonise** [comment]
`require': cannot load such file -- simple_form (LoadError)
