### ISSUE TITLE
wrapper_mappings options not transmitted to simple_fields_for

### ISSUE THREAD

**Issue by Dagnan** [heartcombo/simple_form#1127]
Hi.
I found out that when you set wrapper_mappings on a form and you use simple_fields_for, you have to specify again the wrapper_mappings options, or else it will use the defaults wrapper instead of the ones defined in the form.

Is that an expected behavior?

**Comment by maddog666** [comment]
Hi,
The bug seem to be still there.
Any updates on this bug?
