### ISSUE TITLE
Orverriding button labels for :submit?

### ISSUE THREAD

**Issue by ghost** [heartcombo/simple_form#117]
Hi, 
I am overriding the buttons labels for submit, 
but it does not seem to work, any clue on the issue?

My code --
<%= f.button :submit, :label=> "#{f.object.new_record? ? 'Create' : 'Update'}" %>

even this --
<%= f.button :submit, :label=> "abcd" %>

Thanks.

**Comment by nthngoc277** [comment]
@lazyspark I updated the value of button and it works for me 

> = f.button :submit, value: "#{f.object.new_record? ? 'Create' : 'Update'}"

I know it may be too late because this answer come from 2017 :D but hopes this helps who needs it later ^_^

**Comment by diegosteiner** [comment]
@nthngoc277 For me, setting a button label with ```value: "Label"``` resulted indeed in the expected label, but changed again when clicked on (due to the ```data-disable-with``` attribute still set to whatever it was before).

However, passing the second argument to ```f.button``` as string worked perfectly, as previously stated by @nashby.

**Conclusion**: To change the label of a button use:

```<%= f.button :submit, 'Label', class: 'btn btn-primary' %>```

**Comment by fercreek** [comment]
![image](https://user-images.githubusercontent.com/6548504/35242307-d2933f16-ff7e-11e7-8512-ae4d58688ecb.png)
To me is not working :(

**Comment by fercreek** [comment]
https://github.com/thoughtbot/administrate/issues/835#issuecomment-301603265
It works!

**Comment by h0jeZvgoxFepBQ2C** [comment]
Hm, sorry to reopen this, but it looks like its a bit broken:

```haml
  =f.button :submit, "Zusage", name: "interaction[acception]", value: "0"
  =f.button :submit, "Absage", name: "interaction[acception]", value: "1"
```

renders

```html
<input type="submit" name="interaction[acception]" value="0" class="btn" data-disable-with="Zusage">
=> Button which shows 0 as label
<input type="submit" name="interaction[acception]" value="1" class="btn" data-disable-with="Absage">
=> Button which shows 1 as label
```

instead of

```html
<button type="submit" name="interaction[acception]" value="0" class="btn" data-disable-with="Zusage">Zusage</button>
<button type="submit" name="interaction[acception]" value="1" class="btn" data-disable-with="Absage">Absage</button>
```

Or am I doing something wrong?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ahh sorry,

one should use the button type:

```haml
  =f.button :button, type: "submit", value: "1", name: "interaction[acception]" do
    Zusage
  =f.button :button, type: "submit", value: "0", name: "interaction[acception]" do
    Absage
```
