### ISSUE TITLE
Collection checkboxes always wrapperd

### ISSUE THREAD

**Issue by c0mrade** [heartcombo/simple_form#1181]
Hello,

It seems that `wrapper_html` option is not functioning at the moment. Take this case for instance :

`= sr.collection_check_boxes :model_checkboxes, [[true, 'Test 1'], [true, 'Test 2'], [true, 'Test 3']], :last, :last, item_wrapper: false`

Still wraps each checkbox and label into an element (span). But this works:

`= sr.collection_check_boxes :model_checkboxes, [[true, 'Test 1'], [true, 'Test 2'], [true, 'Test 3']], :last, :last, item_wrapper_class: 'test'`

It adds the `test` class to each checkbox wrapper. It seems there is no way of getting rid of this wrapper for each checkbox + label. Is this a bug?

**Comment by carlosantoniodasilva** [comment]
@c0mrade for that I believe you can use `collection_check_boxes` with a block, like in [this example](https://github.com/plataformatec/simple_form/blob/v3.1.0/lib/simple_form/form_builder.rb#L392-L396). 

This will yield a "builder" where you can call

**Comment by hackeron** [comment]
Before updating to the latest version of simple_form, this code:

```ruby
= f.input_field :time_of_day,
            collection: [:all, :morning, :afternoon, :evening, :night],
            checked: params[:events][:time_of_day],
            as: :radio_buttons, item_wrapper_class: 'button secondary small'
```

Generated this:

```html
<label class="radio button secondary small">
  <input class="radio_buttons required" id="events_time_of_day_business_hours" item_wrapper_class="button secondary small" name="events[time_of_day]" type="radio" value="business_hours"> Business Hours
</label>
```

Now the same code generates:

```html
<span class="radio button secondary small">
  <label for="events_time_of_day_business_hours">
    <input item_wrapper_class="button secondary small" class="radio_buttons required" type="radio" value="business_hours" name="events[time_of_day]" id="events_time_of_day_business_hours"> Business Hours
  </label>
</span>
```

How do I override this to get the old behaviour?
