### ISSUE TITLE
using multibytes in collection breaks label's for and input's id attributes

### ISSUE THREAD

**Issue by github0013** [heartcombo/simple_form#1347]
``` bash
$ uname -a
Darwin mbp 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64

$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
```

created a repo to test.
https://github.com/github0013/simple_form_check_boxes

``` ruby
# app/views/users/create.html.erb

<%= simple_form_for User.new do |f| %>
  <%= f.input :tags, as: :check_boxes, collection: %w[tag1 tag2 tag3] %>
  <%= f.input :tags, as: :check_boxes, collection: %w[タグ１ タグ２ タグ３] %>
  <%= f.input :tags, as: :check_boxes, collection: Hash[*(%w[タグ１ タグ２ タグ３]).zip(1..3).flatten] %>
  <%= f.input :tags, as: :check_boxes, collection: Hash[*(%w[タグ１ タグ２ タグ３]).zip(%w[タグ１ タグ２ タグ３]).flatten] %>
<% end %>

```

While `collection: %w[tag1 tag2 tag3]` works as expected, `collection: %w[タグ１ タグ２ タグ３]` doesn't work properly when clicking on labels.

If you check the source, you will see the label `for` and input `id` are all same.  They are missing suffix part which should have been each of the collection text since the `%w[タグ１ タグ２ タグ３]` collection consists of **multibytes**.

Is there a way to fix this with some options?
**NOTE: tag texts itself should be sent to server, not some ids**

**Comment by nashby** [comment]
this was fixed in Rails https://github.com/rails/rails/commit/d656097734928e1f6b3c3bd884e128c4e299f2ec
