### ISSUE TITLE
How to sort an association by label?

### ISSUE THREAD

**Issue by camilleroux** [heartcombo/simple_form#152]
Hi,

I'd like to sort an association select list using the label. Here is my code (the value is the country code) :
    f.association :company_address_country, :prompt => "Choose a country", :label_method => :label, :value_method => :name
How can I sort the list by label?

Thanks

**Comment by funkdified** [comment]
Now try `Country.all.order( :name)`

**Comment by marinaangeli** [comment]
> Now try `Country.all.order(:name)`

Worked beautifuly. Thank you!
