### ISSUE TITLE
Selected values are not working as expected in multiple: true 

### ISSUE THREAD

**Issue by Rubioli** [heartcombo/simple_form#1627]
In my form, I have an `f.select` with `multiple: true`, but `select` doesn't work if it's not *hardcoded* in.

*This is my form in `new` view:*

    = f.select :os, get_uniq_objects(:os), {}, {multiple: true }

*My helper*

    def get_uniq_objects(obj)
      somethings.pluck(obj).uniq
    end

*My controller*

    def campaign_params
          params.require(:something).permit(os:[])
    end

In `new` view, when OSs are selected, the result would saved as `['Linux', 'Windows']` so in my `edit` view I do as below **but** nothing gets selected:

    = f.select :os, options_for_select(get_uniq_objects(:os), @something.os), {}, { multiple: true}

**BUT** if I *hardcode* them as below, everything works fine. I've even double checked what `@something.os` is by adding it to my view and its exactly like the *hardcoded* code.

    = f.select :os, options_for_select(get_uniq_objects(:os), ['Linux', 'Windows']), {}, { multiple: true}

I'm not sure what I've done wrong here. Any help is appreciated and thanks in advance!

> PS: My investigation showed me that the value passed to `f.select` was as follow:
> `["Linux", "Windows"]`
> But `f.select` for some reason, added backslashes to them and converted to:
> `[\"Linux\", \"Windows\"]`

- Rails **4.2.4**
- Simple Form **4.1.0**

**Comment by feliperenan** [comment]
Hi @Rubioli 

Could you please provide us a sample application that reproduces the issue in isolation? 

That would help us find the issue.
