### ISSUE TITLE
CollectionCheckBoxes cannot handle Date properly

### ISSUE THREAD

**Issue by eloyesp** [heartcombo/simple_form#1643]
## Environment

- Ruby **[version]**: ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
- Rails **[version]**: Rails 5.0.7
- Simple Form **[version]**: simple_form (4.1.0)

## Current behavior

It seems that check_boxes collection input does not properly handle dates, at least the result differ when using that instead of a select multiple.

A minimal example could be:

``` ruby

# in the form
collection = ['2019-01-01', '2018-01-01'].map{ |d| Date.parse(d) }
f.input :testing, collection: collection, as: :check_boxes
f.input :testing, collection: collection, input_html: { multiple: true

# in the model
class TheModel
  def testing
    [Date.parse('2018-01-01')]
  end
end
```

The problem is that the date 2018-01-01 is "selected" within the multiple select field, but the corresponding checkbox is unchecked.

```html
<fieldset class="form-group check_boxes optional metric_testing form-group-valid">
    <legend class="col-form-label pt-0">Testing</legend><input type="hidden" name="metric[testing][]" value="" />
    <div class="form-check"><input class="form-check-input check_boxes optional" type="checkbox" value="2019-01-01" name="metric[testing][]" id="metric_testing_2019-01-01" /><label class="collection_check_boxes" for="metric_testing_2019-01-01">2019-01-01</label></div>
    <div class="form-check"><input class="form-check-input check_boxes optional" type="checkbox" value="2018-01-01" name="metric[testing][]" id="metric_testing_2018-01-01" /><label class="collection_check_boxes" for="metric_testing_2018-01-01">2018-01-01</label></div>
</fieldset>
<div class="form-group row select optional metric_testing form-group-valid"><label class="col-sm-3 col-form-label select optional" for="metric_testing">Testing</label>
    <div class="col-sm-9"><input name="metric[testing][]" type="hidden" value="" /><select class="form-control select optional" multiple="multiple" name="metric[testing][]" id="metric_testing"><option value="2019-01-01">2019-01-01</option>
<option selected="selected" value="2018-01-01">2018-01-01</option></select></div>
</div>
```

I would expect the output to match.

Regards

**Comment by feliperenan** [comment]
Could you please provide us a sample application that reproduces the issue in isolation? 

That would help us find the issue.

**Comment by eloyesp** [comment]
@feliperenan I don't have a sample application, but I was able to write a [falling test](https://github.com/plataformatec/simple_form/compare/master...eloyesp:date_valued_checkboxes_collection) in [this commit](https://github.com/plataformatec/simple_form/commit/f7c9ff9de6f62a7a877c70dfe83d772a3a2a9c26).

I've also found that using `:to_date` as value method makes it work as a workaround. It seems that the value is getting transformed to string twice.

**Comment by nashby** [comment]
It's not a SimpleForm's issue but Rails's. Will be fixed by this https://github.com/rails/rails/pull/44564
