### ISSUE TITLE
Skip valid_class check if no class defined

### ISSUE THREAD

**Issue by TALlama** [heartcombo/simple_form#1656]
## Environment

- Ruby 2.6.2
- Rails 5.1.7
- Simple Form 4.1.0

## Current behavior

We have a simple file input in our form:

```rb
<%= form.input :content, as: :file %>
```

As of 4.1, this is now a performance problem, because the file in question is stored in S3, and each time we render this form we now fetch the file from S3 to check if it's present, because `simple_form` wants to add the `valid_class`. In our case this is one of several such forms on the same page, which is now prohibitively slow.

We have defined `valid_class: nil` in our wrapper config, but `simple_form` still does the work to determine validity even if no class will be added if we are valid. We also marked the field as `required: false` in hopes that it being optional would allow it to be valid when it's not present, but that doesn't affect anything either.

This is very similar to #1596, except that only talks about getting rid of the CSS class, whereas I want to go a step further and avoid doing the (sometimes expensive) work that determines if a CSS class is necessary.

## Expected behavior

If `valid_class` is `nil` (in the wrapper config or in the input options), no validity check should be performed.

**Comment by marcelolx** [comment]
@TALlama I think this issue can be closed, right?

**Comment by feliperenan** [comment]
Oh yeah, it seems closed. Thanks :)
