### ISSUE TITLE
Request: Make label: false remove the entire legend element for collections

### ISSUE THREAD

**Issue by OscarHeller** [heartcombo/simple_form#1664]
Based off my StackOverflow: https://stackoverflow.com/questions/56728460/how-do-i-hide-the-form-title-that-appears-inside-a-legend-tag-when-generating-ch

The behavior I'd like: for label: false to completely remove the legend element. label: '' correctly sets the text to an empty string but it leaves behind the legend element, which has padding. Unless there's syntax I don't know about, label: false removing the legend element seems like natural and useful behavior.

**Comment by sobrinho** [comment]
Poking around I found that using `legend_tag: false` does the job, probably missing documentation.

**Comment by sobrinho** [comment]
In the principle of least surprise I would expect the same to happen when using `label: false`, maybe we can do a translation of that or if that's not what we want, at least a warning/error when using `label: false` when using `f.association`.

**Comment by feliperenan** [comment]
Hi :wave: 

Thanks for the report, as said above, you should be able to disable it with `legend_tag: false`. If it doesn't work for you, could you please send a sample application that reproduces this issue in isolation?

For now, I'm gonna close this issue.

Thanks

**Comment by sekrett** [comment]
`legend_tag: false` works but still it is missing in the documentation.

**Comment by ducuyusuke** [comment]
hey guys I just found this and its still nowhere to be found in the documentation lol
sorry to necro
