### ISSUE TITLE
undefined method `extending' for #<Class:xxx>

### ISSUE THREAD

**Issue by rnickmccandless** [heartcombo/simple_form#1669]
## Precheck

- This is relating to closed issue https://github.com/plataformatec/simple_form/issues/1264, but this bug still exists.

## Environment

- Ruby **2.4.1**
- Rails **5.0.7**
- Simple Form **4.1.0**

## Current behavior

For the following code:

```erb
<%= simple_form_for @entity do |f| %>
   [...]
   <%= f.association :configuration_roles %>
   [...]
<% end %>
```

...is raising an error:

> undefined method `extending' for #<Class:xxx>

The "Class" is the associated model that has an `extending` function, which is supported by the Rails framework (https://guides.rubyonrails.org/association_basics.html#association-extensions):

```ruby
class ConfigurationRole < ApplicationRecord
  [...]
  has_and_belongs_to_many :entities
  [...]
end

class Entity < ApplicationRecord
  [...]
  has_and_belongs_to_many :configuration_roles, -> { extending ::ConfigurationRoleExtension }
  [...]
end
```

## Expected behavior

The expected behavior is allowing the `associations` to pull the associated data without having SimpleForm raise the `NoMethodError`.

**Comment by feliperenan** [comment]
Hi @rnickmccandless thank you for the report.

Could you please provide us a sample application that reproduces the issue in isolation? 

That would help us find the issue.
