### ISSUE TITLE
Feature request: add option to add custom tag in nested boolean checkboxes

### ISSUE THREAD

**Issue by quorak** [heartcombo/simple_form#1678]
I hav a existing design with styled checkboxes and switches which needs a `span` after the input, within the label. From the code I don't see a option to easily add it. I will create a PR.
```
<label class="kt-checkbox kt-checkbox--bold kt-checkbox--success">
        <input type="checkbox"> Label text
        <span></span>
</label>
```

**Comment by feliperenan** [comment]
I'm not sure if that's possible either, but you definitely should be able to achieve that with your custom component:

https://github.com/heartcombo/simple_form#custom-components

Hope it helps :crossed_fingers: 

Thanks :)
