### ISSUE TITLE
Installing with --bootstrap flag gives misleading advice

### ISSUE THREAD

**Issue by goalaleo** [heartcombo/simple_form#1687]
## Environment
- Simple Form **5.0.1**

## Current behavior
Running `rails generate simple_form:install --bootstrap` produces this output
```
===============================================================================

  Be sure to have a copy of the Bootstrap stylesheet available on your
  application, you can get it on http://getbootstrap.com/.

  Inside your views, use the 'simple_form_for' with the Bootstrap form
  class, '.form-inline', as the following:

    = simple_form_for(@user, html: { class: 'form-inline' }) do |form|

===============================================================================
```
from https://github.com/heartcombo/simple_form/blob/3a99d65b082c4422e2f761b1a01e35dee9bd69ae/lib/generators/simple_form/templates/README
## Expected behavior
I don't understand why the output instructs to use the `form-inline` class. This is almost never the [style](http://simple-form-bootstrap.plataformatec.com.br/examples/inline) of form that is used, and the fact that it was mentioned as part of the installation made me think that it's somehow integral to how simple form works with Bootstrap

**Comment by feliperenan** [comment]
Hi @goalaleo thanks for the issue reporting.

Even though it's just a suggestion, I agree with you that we could improve this message explaining that User's could remove or use any other class supported by bootstrap that they want to. Feel free to open a pull-request for that 👍
