### ISSUE TITLE
Extract only input from a generator f.association and use span correctly

### ISSUE THREAD

**Issue by geonizeli** [heartcombo/simple_form#1692]
## Precheck
The way the html is generated makes it unable to use many css frameworks.

## Environment

- Ruby **[2.6.1]**
- Rails **[6]**
- Simple Form **[5.0.2]**

## Current behavior
```
  <span class="checkbox">
    <label for="subject_course_ids_2">
      <input class="check_boxes optional"
             type="checkbox"
             value="2"
             checked="checked"
             name="subject[course_ids][]"
             id="subject_course_ids_2">
      teste
    </label>
  </span>
```
## Expected behavior
give only 'input'
f.association :courses, as: :check_boxes, only_input: true
result: 
```
<input class="check_boxes optional"
           type="checkbox"
           value="1"
           checked="checked"
           name="subject[course_ids][]"
           id="subject_course_ids_1"/>

```
OR:
f.association :courses, as: :check_boxes, mdn: true
result:
```
  <label for="subject_course_ids_1">
    <input class="check_boxes optional"
           type="checkbox"
           value="1"
           checked="checked"
           name="subject[course_ids][]"
           id="subject_course_ids_1"/>
    <span>CCOMP<span>
  </label>
```

**Comment by geonizeli** [comment]
Sorry my stupidity, I didn't see the existence of the label: false, but apparently it didn't work for me.

**Comment by geonizeli** [comment]
Span use reference:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/span

**Comment by rafaelfranca** [comment]
Thank you for the issue. All you asked is already possible with Simple Form.

If you don't want the span wrapping the input or want a different tag you can set the `item_wrapper_tag` option.

If you only want the input without the label you have many options:

* Use the wrappers API to define a wrapper that only generate the input.
* Or use the `input_field` method.

Please take a look in the README and documentation to learn about those.

**Comment by rafaelfranca** [comment]
Speaking on using span correctly. In the referense you sent it says that the content of a span can be any Phrasing content. A `label` is a valid Phrasing content. https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content

**Comment by geonizeli** [comment]
> Speaking on using span correctly. In the referense you sent it says that the content of a span can be any Phrasing content. A `label` is a valid Phrasing content. https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content

Thanks for elucidation! :smile:
