### ISSUE TITLE
simple_form - dots under stars for required fields

### ISSUE THREAD

**Issue by ecustovic** [heartcombo/simple_form#1698]
## Precheck

Hi,
I would be so thankful if you could help me solve problem I have in my project. While implementing my task I have used simple_form and it has proved as an excellent solution until I have tried to deploy pull request. So, locally it all worked fine and I have override default design the way my application requires, but after while testing on Review app it seems like my custom made class for abbr[title] has been removed so I got this (Current behavior block)
instead of this: (Expected behavior block)
Found some experiences on web but didn't help (https://stackoverflow.com/questions/6748446/rails-simple-form-gives-dots-under-stars-for-required-fields-better-way-to-remo)
Hope you can help me solve this!
## Environment

- Ruby 2.6.5p114
- Rails 6.0.2.2
- Simple Form 5.0.2

## Current behavior
![image](https://user-images.githubusercontent.com/41287225/80839137-eb0ffd80-8bfa-11ea-829c-1fe940725373.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/41287225/80839078-ca47a800-8bfa-11ea-84ef-98b38373a60d.png)

**Comment by feliperenan** [comment]
@ecustovic Thanks for the report 🙌

I'd love to help but I don't even have rails installed here 🙈 . Could you send an example application that reproduces this issue in isolation? It would make things a lot easier to help you.

Thanks

**Comment by ptcodes** [comment]
The dots are added by your browser as the default style. This has nothing to do with simple_form.
You can simply overwrite it by:

abbr {
  text-decoration: none;
}

**Comment by feliperenan** [comment]
Thanks @ptcodes

**Comment by lain0** [comment]
This worked for me to remove that dots completly:
```css
abbr[title] {
  text-decoration: none;
  border-bottom: 0;
}
```
