### ISSUE TITLE
Forms using simple_fields_for with boolean inputs displaying raw html.

### ISSUE THREAD

**Issue by tfmcloughlin** [heartcombo/simple_form#1702]
## Environment

- Ruby 2.4.9
- Rails 5.1.7
- Simple Form 5.0.2

## Current behavior

Please find my associated pull request here: https://github.com/heartcombo/simple_form/pull/1703

Under some circumstances when using boolean inputs from inside a `simple_fields_for` block, escaped html is being rendered rather than the correct html output. So, html text appears in the form rather than the actual form controls.

The cause appears to be in the method #build_hidden_field_for_checkbox of the SimpleForm::Inputs::BooleanInput class returning a String instead of an ActiveSupport::SafeBuffer:

```ruby
def build_hidden_field_for_checkbox
  return "" if !include_hidden? || !unchecked_value
  options = { value: unchecked_value, id: nil, disabled: input_html_options[:disabled] }
  options[:name] = input_html_options[:name] if input_html_options.key?(:name)
  options[:form] = input_html_options[:form] if input_html_options.key?(:form)

  @builder.hidden_field(attribute_name, options)
end
```

I believe the return guard on the first line of the method should be : 
```ruby
return "".html_safe if !include_hidden? || !unchecked_value
```

I believe returning a html safe ActiveSupport::SafeBuffer here stops the final output being converted to a String, because of the behaviour of the (+) operator: 

```ruby
unsafe = "test"
unsafe.class                  
# => String

safe = "test".html_safe
safe.class                  
# => ActiveSupport::SafeBuffer

(unsafe + safe).class     
# => String

(safe + unsafe).class     
# => ActiveSupport::SafeBuffer
```

## Expected behavior

1 ) The method `build_hidden_field_for_checkbox` always returns an ActiveSupport::SafeBuffer.
2) Forms using boolean inputs rendered inside a `simple_fields_for` block render correctly.

Thank you.

**Comment by nashby** [comment]
closed by https://github.com/heartcombo/simple_form/pull/1703
