### ISSUE TITLE
Turn off default data-disable-with for submit button

### ISSUE THREAD

**Issue by augustosamame** [heartcombo/simple_form#1713]
## Environment

- Ruby **2.5.1**
- Rails **5.2.1**
- Simple Form **5.0.1**

## Current behavior

simple_form adds data-disable-with by default to generated submit buttons
there is no way (that I have found) to disable this behaviour

## Expected behavior

data-disable-with works fine for most scenarios. However, in my application, I am using send_data in my controller as a result of the form submit. This has the effect of leaving the submit button in a disabled state.

There should be a way to disable simple_form's default behavior of adding data-disable-with to the submit button without having to result to javascript shenanigans

**Comment by carlosantoniodasilva** [comment]
The `data-disable-with` default is provided by Rails `submit` implementation, not SimpleForm. See https://api.rubyonrails.org/classes/ActionView/Helpers/FormTagHelper.html#method-i-submit_tag.

You can disable it on a case-by-case basis by passing in `data: { disable_with: false }` to your button via SimpleForm / Rails, or globally by setting `config.action_view.automatically_disable_submit_tag = false` in your app config.
