### ISSUE TITLE
add new locales to config/locales

### ISSUE THREAD

**Issue by yshmarov** [heartcombo/simple_form#1717]
Why do we currently only have `simple_form.en.yml` included by the gem by default in [config/locales](https://github.com/heartcombo/simple_form/tree/master/lib/generators/simple_form/templates/config/locales)?

Most projects that include `i18n` have to manually create a `simple_form.#{language}.yml` file and find it in google...

If accepted, I could help to add a few more default locales to the folder

**Comment by rafaelfranca** [comment]
Thank you for the request but we don't have interest on including any other locale in this gem by default.
