### ISSUE TITLE
bootstrap 5 support

### ISSUE THREAD

**Issue by yshmarov** [heartcombo/simple_form#1732]
In bootstrap 5 the following form:
```
<%= simple_form_for(@plan) do |f| %>
  <%= f.input :currency, collection: [ "usd", "eur", "pln", "uah", "rub"], include_blank: false %>
  <%= f.input :interval, collection: ["month", "year", "forever"], as: :radio_buttons %>
  <%= f.input :max_members %>
  <%= f.button :submit %>
<% end %>
```
provides this view:
![image](https://user-images.githubusercontent.com/13472945/112235229-81e40f00-8c3e-11eb-98de-3af4442869df.png)

Below is the same code with bootstrap 4. As you see in the image **above** the collection dropdown does not work + radio buttons are floating around
![image](https://user-images.githubusercontent.com/13472945/112235146-56612480-8c3e-11eb-822f-8b038074ad90.png)

**Comment by carlosantoniodasilva** [comment]
Please report issues with bootstrap 5 to the simple-form-bootstrap repo, it seems there's already an ongoing issue around supporting it there: https://github.com/heartcombo/simple_form-bootstrap/issues/323.

Thanks.

**Comment by yshmarov** [comment]
wasn't aware of its' existance. thanks!
