### ISSUE TITLE
undefined method `setup' for SimpleForm:Module (NoMethodError)

### ISSUE THREAD

**Issue by deepakmahakale** [heartcombo/simple_form#1735]
undefined method `setup' for SimpleForm:Module (NoMethodError)

## Environment

- Ruby **ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]**
- Rails **6.1.3.2**
- Simple Form **5.1.0**

## Current behavior

Works with `rails s` but when I try to run `rails test` I get the following error
```console
$ rails test

/Users/deepak/project/config/initializers/simple_form.rb:10:in `<main>': undefined method `setup' for SimpleForm:Module (NoMethodError)
```

## Expected behavior

Should be able to run `rails test`

**Comment by feliperenan** [comment]
Hi @deepakmahakale 👋🏻 

Are you able to reproduce it in new Rails app? If so, would you mind send a sample repo so we can take a look at?

Thanks 🙌🏻

**Comment by deepakmahakale** [comment]
Sure, I will try the same in the new rails app and share the repo here.

Thanks for the quick response.

**Comment by deepakmahakale** [comment]
@feliperenan 

It is working in a new rails app. But not in my main application.

I went back and tried manually requiring `simple_form`  in the initializers and it is working.
Not sure if it's because of some config, autoloader setting, or something else.

```ruby
# config/initializers/simple_form.rb
require 'simple_form'

SimpleForm.setup do |config|
  # ....
  # ....
end
```

**Comment by carlosantoniodasilva** [comment]
How is simple form listed in your Gemfile? And how is Bundler requiring things in your config/application? Bundler should be requiring all gems on the current environment correctly including simple form, unless you're explicitly saying "require: false".

**Comment by deepakmahakale** [comment]
My bad!!

In a hurry, I had added it in the `development` block.
I spent almost an hour figuring out the issue.

Thanks for the support @carlosantoniodasilva @feliperenan
