### ISSUE TITLE
Minor message error on rails generate simple_form:install --bootstrap

### ISSUE THREAD

**Issue by MtnBiker** [heartcombo/simple_form#1737]
The following appears in Terminal. Link is wrong.  
For usage examples and documentation, see:

    http://simple-form-bootstrap.plataformatec.com.br/

**Comment by carlosantoniodasilva** [comment]
Thanks ❤️💜💛💚💙 , I pushed a fix to point to the Heroku app directly now.

**Comment by MtnBiker** [comment]
Great quick response.
