### ISSUE TITLE
bootstrap 5 does not know sr-only anymore

### ISSUE THREAD

**Issue by estani** [heartcombo/simple_form#1741]
https://github.com/heartcombo/simple_form/blob/2fa860e5f607da307570df75cf57b3684f82e23c/lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb#L255

`sr-only` should be just changed to `visually-hidden` (https://getbootstrap.com/docs/5.0/helpers/visually-hidden/)

(sorry this is faster than forking & co... hope is still ok)

**Comment by carlosantoniodasilva** [comment]
We have a PR in the works for full bootstrap 5 support: #1738, please feel free to give that one a shot and report any issues to https://github.com/heartcombo/simple_form-bootstrap. Thanks.
