### ISSUE TITLE
The first option for radio button is not rendered correctly

### ISSUE THREAD

**Issue by Yoshihisa19920807** [heartcombo/simple_form#1743]
## Environment

- Ruby **3.0.2**
- Rails **6.1.4**
- Simple Form **5.1.0**

## Current behavior

The first button is rendered within the label div as the following image
https://i.imgur.com/LCuKefZ.png

## Expected behavior
The first button should be rendered outside the label

**Comment by khangvinhle** [comment]
Having the same issue

**Comment by dblanken** [comment]
Mine seems to be an issue with the float css attribute on the legend tag from Bootstrap 5.  If you overwrite it with float: none, it looks as I expect.

**Comment by nashby** [comment]
Hey! It's not really a SimpleForm's issue but Bootstrap's. See how's it's handled in https://github.com/heartcombo/simple_form-bootstrap/blob/a130302e607c913fc7b578b3b180e40166218e32/app/assets/stylesheets/simple_form-bootstrap/_form_legend_clear.scss
