### ISSUE TITLE
`rails generate simple_form:install --bootstrap` freezes on Window's WSL

### ISSUE THREAD

**Issue by Naokimi** [heartcombo/simple_form#1747]
**Environment:**
- Windows WSL2 dev environment (setup based on https://github.com/lewagon/setup/blob/master/windows.md)
- ruby 2.7.2
- rails 6.1.4.1
- simple_form 5.1.0

**Reproduction steps:**
1. create new app (e.g. `rails new app_name -T -d=postgresql`)
2. add gems `'simple_form'` and `'bootstrap', '~> 5.1.0'`
3. run `rails generate simple_form:install --bootstrap`
4. remove folder and all contents (either delete in explorer or `-rm -rf`)
5. recreate app with same name (e.g. `rails new app_name -T -d=postgresql`)
6. add gems `'simple_form'` and `'bootstrap', '~> 5.1.0'`
7. run `rails generate simple_form:install --bootstrap`

**Result:**
Command freezes and won't finish generation
![image](https://user-images.githubusercontent.com/49295880/133056932-71793b50-3345-4f5d-aafd-25eaa19fc8eb.png)

**Comment by Naokimi** [comment]
just noticed that this might be a rails issue as generating models or controllers also freezes

**Comment by yannklein** [comment]
A `spring stop` solved the issue on my side 👍
