### ISSUE TITLE
Missing form-select on bootstrap simple forms

### ISSUE THREAD

**Issue by alex-benoit** [heartcombo/simple_form#1752]
## Environment

- Ruby **3.0.2**
- Rails **6.1.4.1**
- Simple Form **5.1.0**

## Current behavior

For bootstrap,

`<%= f.input :channel, collection: @stuff %>`

generates a select but just add the `form-control` class

![image](https://user-images.githubusercontent.com/16181471/146183590-88d1455b-34d7-43a0-9249-99b70e5cf922.png)

## Expected behavior

The bootstrap `form-select` class should be added

![image](https://user-images.githubusercontent.com/16181471/146183636-d1f025cf-f21e-4354-b8b8-a393a3b04590.png)

**Comment by gdonald** [comment]
I ran into this also.  Not sure how to "fix it" as adding a customization in `simple_form_bootstrap.rb` like `b.use :select, class: 'form-select'` breaks all my instances of `f.input ...`.

**Comment by nashby** [comment]
It works now.

**Comment by pioneerskies** [comment]
@nashby as far as I can see, it works now **on main**, but not in 5.1.0 (latest) release.

- 5.1.0 [was released](https://rubygems.org/gems/simple_form/versions) on 9 Feb 21
- 87c60c56bd122775d85412b29cee7c837941f8b5 shipped on 28 May 21

I've just made a poor man test:

- had the problem
- updated my `Gemfile` with `gem 'simple_form', github: 'heartcombo/simple_form', branch: 'main'`
- `bin/rails g simple_form:install --bootstrap` overwriting previous config
- now it works

I don't know if project's policy is to consider an issues to be resolved when the fix hits `main` and don't know if you'd like to have a new issue filled or, finally, if I'm wrong :)

**Comment by f16z** [comment]
I spent too much time trying to fix this, hopefully gets put into a stable release soon.

thanks.
