### ISSUE TITLE
check_boxes, array first element is empty

### ISSUE THREAD

**Issue by Dalyl09** [heartcombo/simple_form#1753]
## Environment

- Ruby **3.0.2*
- Rails **6.1.4**
- Simple Form **5.1.0**

## Current behavior
In my form :   <%= fd.input :user_id, as: :check_boxes,collection:User.all.map{|s|[s.username, s.id]} %>

## Expected behavior
In my log : {"user_id"=>["", "2", "4"]}
First element is empty.

**Comment by nashby** [comment]
It's not a bug. It's a Rails' feature. You can read more about this on [simple form issue #603](https://github.com/plataformatec/simple_form/issues/603) and [Rails issue #5402](https://github.com/rails/rails/issues/5402)
