### ISSUE TITLE
Change the Bootstrap classes used: collision between the initializers

### ISSUE THREAD

**Issue by collimarco** [heartcombo/simple_form#1756]
Run:

```
rails generate simple_form:install --bootstrap
```

Now you have two initializers.

Suppose that you want to set this:

```
config.button_class = 'btn btn-lg btn-primary px-5'
```

**Option 1 - Set it in Bootstrap initializer**

You should not do that, as documented in the file:

```
Please do not make direct changes to this file!
```

**Option 2 - Set it in default initializer**

In this case setting the value has not effect, because the other initializer is taking over.

**Basically, if you follow the official instructions, there is no way to customize the Bootstrap forms :(**

**Comment by m5o** [comment]
The initializers are of course meant to be customized if the provided defaults do not fit.

You are welcome to submit a PR with your suggestion.

**Comment by collimarco** [comment]
Thanks for the replies. 

Finally I have modified the Bootstrap initializer (the only option that works). 

The only strange thing for this approach is that there is a writing "_Please do not make direct changes to this file!_", which is misleading in my opinion. That file can be customized. I see no other solution.

If I am missing something and there's a better approach please let me know.

**Comment by m5o** [comment]
Understand your point. From this view, it is indeed misleading. This sentence had a different intention.
Will start to address this in [heartcombo/simple_form-bootstrap](https://github.com/heartcombo/simple_form-bootstrap) shortly.
Thank you for the report.
