### ISSUE TITLE
Invalid http address after installation 

### ISSUE THREAD

**Issue by GWakabayashi** [heartcombo/simple_form#1773]
## Environment

- Ruby 3.0.0
- Rails 7
- Simple Form 5.1

## Current behavior

After running  **_rails generate simple_form:install --bootstrap_**  in the terminal, an invalid HTTP address gets printed: 

For usage examples and documentation, see:

    http://simple-form-bootstrap.plataformatec.com.br/

## Expected behavior

The correct address is: 

For usage examples and documentation, see:

    https://simple-form-bootstrap.herokuapp.com/documentation

**Comment by nashby** [comment]
It was fixed by https://github.com/heartcombo/simple_form/commit/123d3b3822cb8a23c6216261f32d5e1af139a087 but not released yet.
