### ISSUE TITLE
Releases missing updated initializers

### ISSUE THREAD

**Issue by twnaing** [heartcombo/simple_form#1774]
[initializer files](https://github.com/heartcombo/simple_form/tree/main/lib/generators/simple_form/templates/config/initializers) are not updated in releases.

Under [main branch](https://github.com/heartcombo/simple_form/tree/main/lib/generators/simple_form/templates/config/initializers), `simple_form.rb` and `simple_form_bootstrap.rb` are 7 months and 2 months old.
Under release (at least [tag 5.1](https://github.com/heartcombo/simple_form/tree/v5.1.0/lib/generators/simple_form/templates/config/initializers)), both files are 2 years old.

[simple_form-bootstrap](https://github.com/heartcombo/simple_form-bootstrap/blob/) repo is already using the main branch initializers.

I cannot produce the examples provided by simple_form-bootstrap using the release gem.

**Comment by nashby** [comment]
Hey, thanks for the heads up! We're aware of it and we'll release it as soon as possible™
