### ISSUE TITLE
Simple form should override default form scaffolding

### ISSUE THREAD

**Issue by gardnerapp** [heartcombo/simple_form#1786]
Generators are one of the best features of Rails. Currently Simple Form does not override the default form generator, which means that if we want to edit or style a form from a generator we would need to rebuild the entire form from scratch. Upon installation, Simple Form should over ride the default Rails form generator thus making the forms easier to edit and deal with in the future. 

Does anyone have any suggestion for where to start?

**Comment by carlosantoniodasilva** [comment]
When you run the [install generator](https://github.com/heartcombo/simple_form#installation), it is supposed to [copy](https://github.com/heartcombo/simple_form/blob/31fe25504771bd6cd425b585a4e0ed652fba4521/lib/generators/simple_form/install_generator.rb#L30-L33) a the [form scaffold template](https://github.com/heartcombo/simple_form/blob/31fe25504771bd6cd425b585a4e0ed652fba4521/lib/generators/simple_form/templates/_form.html.erb#L1) to your app, and Rails should pick that up whenever you run new scaffolds going forward.

Are you looking for another generator?

**Comment by gardnerapp** [comment]
To clarify, when I run the install generator it is not copying the simple_form template to the scaffold template.

System configurations: 
```
ruby "3.1.1"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.3", ">= 7.0.3.1"

gem 'simple_form'
```

Commands :
```
rails g simple_form:install
rails g scaffold Foo bar
```

output:
Default form scaffolding is still present (shown below)
```
<%= form_with(model: foo, class: "contents") do |form| %>
  <% if foo.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(foo.errors.count, "error") %> prohibited this foo from being saved:</h2>

      <ul>
        <% foo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :bar %>
    <%= form.text_field :bar, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>
````

Expected output:
Running ``` rails g simple_form:install ``` should copy the simple_form template to my form scaffolding template

**Comment by gardnerapp** [comment]
** Update **
I just created a fresh app and the template generator worked, I have no idea why the generator wasn't invoked in my previous application. I thought that the issue might have had something to do with the simple_form-tailwinded gem so I once again ran the installation commands and the generator was invoked, simple_form seems to be working properly.
