### ISSUE TITLE
Simple_form generator for Bootstrap 5 problem

### ISSUE THREAD

**Issue by hoangdd** [heartcombo/simple_form#1787]
## Environment

- Ruby **[2.7.5]**
- Rails **[7.0.3.1]**
- Simple Form **[5.1.0]**
- Bootstrap gem **[5.2.0]**
## Current behavior

After running `rails generate simple_form:install --bootstrap`,  I got initializer config `config/initializers/simple_form_bootstrap.rb` file look likes Bootstrap 4 compatible configuration( with `.form-group` wrapper ).
<img width="1059" alt="Screen Shot 2022-08-03 at 2 56 05 PM" src="https://user-images.githubusercontent.com/3371309/182534937-9d80b9f5-2f25-49fe-82a8-1f27cdf2de34.png">
 
And the HTML output with `.form-group` wrapper.

<img width="1585" alt="Screen Shot 2022-08-03 at 2 59 30 PM" src="https://user-images.githubusercontent.com/3371309/182535264-45bceb40-006e-4eb5-adb7-bef711c67405.png">

## Expected behavior
Expecting generator can create config file with bootstrap 5 support content. Same as example at [simple_form-bootstrap/blob/main/config/initializers/simple_form_bootstrap.rb](https://github.com/heartcombo/simple_form-bootstrap/blob/main/config/initializers/simple_form_bootstrap.rb) 

## Problem demo
[https://github.com/hoangdd/simple_form_demo](https://github.com/hoangdd/simple_form_demo)

Thanks for your amazing work.

**Comment by spilth** [comment]
Encountered this as well. Looks like the released gem contains an outdated generator for bootstrap.

My temporary working
1. Change the Gemfile entry to `gem "simple_form", github: "heartcombo/simple_form", branch: "main"`
2. `bundle install`
3. `rails generate simple_form:install --bootstrap`
4. Change the Gemfile entry back to `gem "simple_form"`
5. `bundle install`

**Comment by nashby** [comment]
Yes, Bootstrap 5 is not released yet. You can use what @spilth suggested for now, thanks!

**Comment by trevorfoxsoft** [comment]
This appears to still be an issue, I've just hit it with the latest version from RubyGems, and fixed it with this method. Is this known?
