### ISSUE TITLE
Form errors with Rails 7 and Turbo do not work

### ISSUE THREAD

**Issue by key88sf** [heartcombo/simple_form#1789]
## Environment

- Ruby **[3.0.0]**
- Rails **[7.0.3.1]**
- Simple Form **[5.1.0]**

## Current behavior
Using a basic input form in a Rails view for a model:
```
= simple_form_for(@image) do |f|
  = f.input :url
  = f.button :submit
```

When there are errors on the model (e.g. create fails due to a validation error on the URL in this case), there are no error classes or visual indication added to the form HTML.

In order to get this to work, Turbo has to be turned off for the form submission:
`= f.button :submit, data: { turbo: false }`

## Expected behavior
Would like SimpleForm to "just work" and show validation errors when Turbo is enabled (which it is by default) in Rails 7 apps.

**Comment by danielricecodes** [comment]
The real question here is what is the difference between `form_with`'s HTML and `simple_form_for`.  A brand new rails app without simple_form works out of the box with Turbo.  Trying to use SimpleForm in the same scaffold app does not work.

**Comment by danielricecodes** [comment]
@key88sf - your controller has to respond with code 422 if you want errors to render correctly.  Without posting your controller code its impossible to help.  

```
    if @image.save
      redirect_to @image, notice: 'Image successfully created.', status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
```

**Comment by danielricecodes** [comment]
This is a duplicate of #1754 and should be closed.

**Comment by key88sf** [comment]
@danielricecodes Ah yes - the `status:` is what was missing on the controller side. Thank you for flagging that.
