### ISSUE TITLE
Test suite incompatibility with Rails 7.1.0.alpha - Failing CI

### ISSUE THREAD

**Issue by petergoldstein** [heartcombo/simple_form#1801]
## Environment

- Ruby 3.1.3
- Rails 7.1.0.alpha (rails/rails, main branch)
- Simple Form Unreleased

## Current behavior

The CI suite fails on the 'custom wrappers on input basis' test in `test/form_builder/wrapper_test.rb`.  This test calls `replace` on the output_buffer object, which is of type `ActionView::OutputBuffer`.

In Rails 7.1.0.alpha the `ActionView::OutputBuffer` class was changed such that it is no longer a subclass of `String`, and now this method is unavailable.

## Expected behavior

Test suite should pass and Simple Form should be compatible with Rails 7.1 in tests.

**Comment by nashby** [comment]
@petergoldstein thanks for reporting it! It was fix as part of https://github.com/heartcombo/simple_form/pull/1782
