### ISSUE TITLE
Problem with Heroku

### ISSUE THREAD

**Issue by Chelsea46** [heartcombo/simple_form#1805]
## Environment

- Ruby **[version]** 3.1.2
- Rails **[version]**  7.0.4.1
- Simple Form **[version]**

## Current behavior
Failing to deploy on Heroku
error message Rake aborted! uninitialized constant SimpleForm

**Comment by carlosantoniodasilva** [comment]
We'd need more information, like the full stacktrace, other gems you might be using, the version, or even an app that reproduces the issue.
