### ISSUE TITLE
Changelog entry needed for 5.2.0

### ISSUE THREAD

**Issue by mohamedhafez** [heartcombo/simple_form#1808]
Hi, it would be great if a changelog entry could be made for 5.2.0 when someone gets a chance!

**Comment by nashby** [comment]
Hey! There's Changelog entry for 5.2.0 https://github.com/heartcombo/simple_form/blob/main/CHANGELOG.md#520

**Comment by carlosantoniodasilva** [comment]
@mohamedhafez thanks. I'll update there, but I think we missed deleting the `master` branch on SimpleForm, so I went ahead and deleted it (I just checked and the other repos like Devise don't have it, so they redirect to `main` automatically.)
