### ISSUE TITLE
Is there any particular reason for the use of `%%` instead of `%` in the ERB template?

### ISSUE THREAD

**Issue by r7kamura** [heartcombo/simple_form#1811]
I'm having a little trouble on applying an ERB linter for ERB templates generated by simple_form gem, as the ERB parser provided by [better_html](https://github.com/Shopify/better-html) doesn't seem to support the `<%% ... %%>` format.

```ruby
require 'better_html'
require 'better_html/parser'
require 'parser'

::BetterHtml::Parser.new(
  ::Parser::Source::Buffer.new(
    'example.erb',
    source: '<%% foo %%>'
  ),
  template_language: :html
).ast
# => 
# s(:document,
#   s(:text,
#     s(:erb,
#       s(:indicator, "%"), nil,
#       s(:code, " foo %"), nil)))
```

- https://github.com/r7kamura/rubocop-erb/issues/16

Unlike the general ERB format, [lib/generators/simple_form/templates/_form.html.erb](https://github.com/heartcombo/simple_form/blob/921ce9c3fc100e1737125ba1b5a2037c03f2de1b/lib/generators/simple_form/templates/_form.html.erb) is using `<%% ... %%>` instead of `<% ... %>` format. Is there any particular reason why this format is used here?

**Comment by nashby** [comment]
@r7kamura hey, that's not a template itself. It's a template that generates another template that is gonna be used when you do e.g `rails g scaffold Post name:string`. So looks like someone just copy pasted it directly into their app instead of using generator.

**Comment by r7kamura** [comment]
I see. Thanks for letting me know, very helpful 👍
