### ISSUE TITLE
:prompt => "..." don't work

### ISSUE THREAD

**Issue by ZhangHanDong** [heartcombo/simple_form#249]
Hi 

   i use rails3.0.6 and simple_form 1.3.1,  

  <pre>
   =  f.input :typee, :collection => link_collect, :label => false, :prompt => "..."
  </pre>

 <pre>
 #link_collect
  def link_collect
     [['web', 1], ['wap', 2], ['iphone', 3], ['android', 4]]
  end

  </pre>

  but, the , :prompt => "..." , is not works for me ...

**Comment by phoet** [comment]
just experienced the same as @olivierlacan if this is still a thing, shouldnt this be reflected in the README?
