### ISSUE TITLE
Fieldset support?

### ISSUE THREAD

**Issue by robotmay** [heartcombo/simple_form#25]
Is it just me, or is simple_form currently missing fieldset support? 
One of my favourite features of Formtastic is the ability to write:

```
semantic_form_for @entry do |f|
  f.inputs "A fieldset" do
    f.input :title
    f.input :body
  end
  f.button :submit
end
```

But I can't see this anywhere in the documentation or class. Consider this a feature request if it doesn't already exist. ;)

**Comment by SebastianVomMeer** [comment]
I want to note that SimpleForm fieldsets could use SimpleForm's I18n lookup approach for legends. That would be a large benefit in my opinion.
