### ISSUE TITLE
wrapper configuration should allow setting data- attributes

### ISSUE THREAD

**Issue by huerlisi** [heartcombo/simple_form#282]
Actual use case is to wrap all label/input pairs into some div with a data-role="fieldcontain" attribute. This is to implement the field container concept in jQuery Mobile as described at http://jquerymobile.com/test/docs/forms/docs-forms.html

I don't have any concrete idea on how the interface should look like. But it could probably be some generic thing to specify any string or html-options, not just a data-role attribute.

Thanks for this nice gem, btw!

Cheers
Simon

**Comment by IlkhamGaysin** [comment]
let's say I need to pass different data attrs to an option of radio button or checkbox, how I can do that? I see I can only set a data attr for over all options.

**Comment by braindeaf** [comment]
I also needed this to add a data-controller to add some Stimulus behaviour to a subset of input groups and nope :(

**Comment by hmasing** [comment]
Came here for the same reason as others - need to tell an input to put data-controller attributes on it's wrapper.

Use case:  Clicking on a checkbox and it's label should trigger the stimulus data controller.
