### ISSUE TITLE
Can't disable single option of select

### ISSUE THREAD

**Issue by mattfordham** [heartcombo/simple_form#301]
So, I am trying the following in order to disable a single option of the outputted select (like the regular collection_select allows for):

f.input :state, :collection => Entry::STATES, :disabled => 'disabled_option'

It is indeed disabling the option with the value of ''disabled_option', but it is also disabling the entire select, and adding a "disabled"
class to the wrapping div.

I just need the one option disabled, not everything. Anyway I could do this?

Matt.

**Comment by davidmles** [comment]
This is still happening.
