### ISSUE TITLE
Conditional validations break "required" field marking

### ISSUE THREAD

**Issue by mattfordham** [heartcombo/simple_form#322]
I am using conditional validations for a multi-step form, very much like this Railscast: http://railscasts.com/episodes/217-multistep-forms.

``` ruby
with_options :if => lambda { |o| o.current_step == "contact" } do |entry| 
  entry.validates :name, :presence => true, :length => {:maximum => 50}
end
```

This causes the automatic "required" field marking to not function. The fields all end up with an "optional" class. The validations still work as expected upon form submission. Is this a known issue? Something I am doing wrong?

**Comment by freemanoid** [comment]
@rosskevin I believe you mean browser validations. Do you have it enabled in simple_form config file?
```ruby
SimpleForm.browser_validations = true
```

**Comment by polymer940c** [comment]
SimpleForm.browser_validations  is under initializers > simple_form > config.browser_validations
