### ISSUE TITLE
check boxes with twitter bootstrap integration

### ISSUE THREAD

**Issue by fschwahn** [heartcombo/simple_form#424]
Hi,
I'm using the latest version (`e6fe814bbe5bb025e0489d3999b872bd936acd94`) from git and there are some problems with check boxes:

![Check box issue](http://i.imgur.com/kvGTw.png)
1. The hint is displayed in the same line as the check box. I guess this is not intended.
2. The label is displayed on the left side of the check box. Is it possible to configure simple_form using the new syntax to display it on the right side? It looks nicer in my opinion.
3. (not related to check boxes, but still) The generated scaffold form generator should use the class `form-actions` instead of `actions` for the buttons when using twitter bootstrap.

The integration is great!

Best regards,
Fabian

**Comment by HninNweOo** [comment]
I want to know how to use twitter bootstrap css in collection_check_boxes.please if you know, tell me.
