### ISSUE TITLE
Default value for date not used with :include_blank => true

### ISSUE THREAD

**Issue by romanoff** [heartcombo/simple_form#425]
Following expression doesn't work for simple_form. Expected date is still blank (it should be only blank if default value is nil)

```
<%= f.input :expected_date, :as => :date, :include_blank => true, :default => Date.today  %>
```

Have also tried to specify :value => <Date>, but didn't work as well

**Comment by Mingus85** [comment]
try `selected: Date.yesterday`. Works with me :-)
