### ISSUE TITLE
Styling the labels for a check box collection

### ISSUE THREAD

**Issue by noctivityinc** [heartcombo/simple_form#452]
I have a simple HABTM relationship between categories and fonts.  A category can have many fonts.  Anyway, in my form I want to display a list of all the fonts with a checkbox next to each of them so I can select the fonts for a category.

The catch is that I want to add the font class to the LABEL for each option so that it is applied.  In this case, the class is an attribute called _class_name_ inside of the font model.

I have this:

```
= f.association :fonts
```

and have tried lots of things, including:

```
= f.association :fonts, :collection => Font.all.map { |o| [o.name, o.id, { :class => "#{o.class_name}" }] }, :as => :check_boxes
```

without luck.  How can I accomplish this?

**Comment by digitalecho** [comment]
Anyone know why I get this output:

```html
<div class="form-group check_boxes optional order_option_ids">
<label class="check_boxes optional control-label" for="order_option_ids"> Health potion option ids</label>
<span>
<label for="order_option_ids_2">
     <label for="order_option_ids_2">
        <input type="checkbox" value="2" name="order[health_potion_option_ids][]" id="order_option_ids_2">Add more caffeine
     </label>
</label>
</span>
```
I am doing this, as stated above but I am getting double labels:

````erb
<%= f.input :category_ids, :as => :check_boxes do %>
  <%= f.collection_check_boxes :category_ids, Category.order(:name), :id, :name do |b|
    b.label { b.check_box + b.text }
  end %>
<% end %>
```

using simple_form (3.1.0)
rails 4.2

**Comment by carlosantoniodasilva** [comment]
@digitalecho please try sending your question to the mailing list, there are more people there that might help.

**Comment by midu** [comment]
same issue as @digitalecho here, did you figure it out?

**Comment by aaronmcadam** [comment]
I'm having the same issue, labels get doubled trying to manually render labels

**Comment by carlosantoniodasilva** [comment]
@aaronmcadam could you provide a sample app showing the issue? Please feel free to open a new issue with the app then, thanks.

**Comment by aaronmcadam** [comment]
Hi @carlosantoniodasilva, thanks for replying. I've created [a new issue](https://github.com/plataformatec/simple_form/issues/1266). It looks like the issue happens when using haml.
