### ISSUE TITLE
turns off the custom wrapper bug

### ISSUE THREAD

**Issue by elfassy** [heartcombo/simple_form#477]
Using

```
# Completely turns off the custom wrapper
f.input :name, :bootstrap => false
```

does not work v2.0.1 (it does nothing). On the other hand,

```
f.input :name, :wrapper => false
```

does remove the control-group div but not the controls div inside it.... Any way to remove both these divs?

**Comment by dragonlive** [comment]
+1 for adding 'wrapper: false'
