### ISSUE TITLE
Wrapping collection check boxes

### ISSUE THREAD

**Issue by sher** [heartcombo/simple_form#50]
Is there a way of wrapping every check box or a radio button in some html tag?
For example:
Set the initializer config:
    SimpleForm.setup do |config|
      ...
      config.collection_check_boxes_wrapper_tag = :li
      ...
    end

and in the view file:
    <ul>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
    </ul>
so every check box gets wrapped in `<li>` tag which can be easily arranged at designer's will.

Or passing the wrapper tag directly in the view as a hash
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, :wrapper => :li %>

p.s. I think there is an error in docs Collection Check Box section
    f.collection_check_box :options, [[true, 'Yes'] ,[false, 'No']], :first, :last
should be
    f.collection_check_boxes :options, [[true, 'Yes'] ,[false, 'No']], :first, :last

**Comment by sledge909** [comment]
Thanks for this @maxschulze 8
