### ISSUE TITLE
Checkbox label on the left?

### ISSUE THREAD

**Issue by n8** [heartcombo/simple_form#500]
Just wanted to see if this was a bug or how it's meant to be. A single checkbox's label appears on the left of the checkbox? Isn't the convention to usually put the label on the right of any checkbox, even if it's by it's lonesome?

![screenshot](https://img.skitch.com/20120304-pwabfyuk5ig5wawgn58f68c2kc.jpg)

**Comment by pjar** [comment]
It's working in 2.1.3, you just need to add all of these:

```
boolean_style: :nested, inline_label: "foo", label: false
```
