### ISSUE TITLE
Check boxes and hidden input problem

### ISSUE THREAD

**Issue by dalizard** [heartcombo/simple_form#603]
Hi guys!

I am using simple_form 2.0.2 with rails 3.2.3. I have a simple model called Movie with a serialized field 'resolutions':

```
class Movie < ActiveRecord::Base
  serialize :resolutions, Array
end
```

The simple_form looks like this:

```
<%= simple_form_for @movie do |f| %>
  <%= f.input :resolutions, :collection => ["SD", "ED", "HD"], :as => :check_boxes %>
<% end %>
```

The problem is, that simple_form adds the following input tag (with no value) after the 3 input tags for the collection:

```
<input name="movie[resolution][]" type="hidden" value>
```

When the form gets submitted with only the "SD" checkbox selected, the params looks like this:

```
"resolutions"=>["SD", ""]
```

and the Movie instance gets updated accordingly:

```
irb(main):022:0> m.resolutions
=> ["SD", ""]
```

The problem is that, I don't want the empty string present in the resolutions field. And in case all checkboxes are uncheck, the params contains "resolutions"=>[""] instead of "resolutions"=>[]. Any suggestions?

**Comment by eikes** [comment]
If you remove the hidden field via ```include_hidden: false``` you will not get anything from the browser when no checkbox is selected. This is a problem when a checkbox had been checked before and you would like to uncheck all boxes now, which will not work. You can try it.

In stead I suggest you clean the array before you save it:

```ruby
class Movie < ActiveRecord::Base
  serialize :resolutions, Array

  before_save :clean_resolutions

  def clean_resolutions
    resolutions.reject { |r| r.blank? }
  end
end
```

**Comment by timshingyu** [comment]
@eikes Thank your suggestion, for your code snippet, need to change `reject` method to `reject!`. Otherwise it won't save it to db.

```
class Movie < ActiveRecord::Base
  serialize :resolutions, Array

  before_save :clean_resolutions

  def clean_resolutions
    resolutions.reject! { |r| r.blank? }
  end
end
```

**Comment by Systho** [comment]
I think we can automatically add this option when the input is disabled or we will have all usual options disabled but the hidden won't which means the collection would always be reset upon save.

I use a custom collection_checkboxes input on my project and I have overriden the `apply_default_collection_options!` method like this 

```
  def apply_default_collection_options!(options)
    super     
    options[:include_hidden] = !options[:disabled]
   # other options related to my custom checkboxes
  end

```

**Comment by adavia** [comment]
I believe this issue persists with rails 5.0.0.1. I am adding include_hidden: false but i still get empty values
```
= f.association :answers, label: false,
  collection: @poll.questions[f.options[:child_index].to_i].answers,
  as: :check_boxes, include_hidden: false
```

**Comment by ncri** [comment]
Still have the same issue with a select. `include_hidden: false` has no effect.

**Comment by scoobyclub** [comment]
Using latest version of rails this worked it for me ( using simple_form ) as it removed the leading "" in the hash.

  <%= f.collection_check_boxes :tags, Tag.all, :tag, :tag, as: :boolean, include_hidden: false %>
