### ISSUE TITLE
Image as label for association 

### ISSUE THREAD

**Issue by crowdvn** [heartcombo/simple_form#607]
I have a Task model and an associated model PaymentMethod which contains some images I intend to use instead of its text label. I tried this: 

```
= simple_form_for @task 
     = f.association :payment_method, :as => :radio_buttons, :label_method => lambda {|p| "#{escape_javascript(image_tag p.image_url)}"}
```

But what it displayed is the image url in plain text.

**Comment by kowo-zahl** [comment]
This issue is top on Google for "simple form image as label" .

= simple_form_for @task 
     = f.association :payment_method, :as => :radio_buttons, :label_method => lambda {|p| image_tag p.image.url}

works.
