### ISSUE TITLE
:disable_with option is not working 

### ISSUE THREAD

**Issue by naveed-ahmad** [heartcombo/simple_form#640]
:disable_with option is not working in submit button.here is code

``` ruby
   f.submit 'Start Your Membership', :class => 'button', :disable_with => 'Please Wait...'
```

and generated markup

```
<input class="button" data-disable-with="Please Wait..." id="user_submit" name="commit" type="submit" value="Start Your Membership">
```

I'm using rails (3.0.7)  and  simple_form (2.0.2)

**Comment by lyushenko** [comment]
Here's a workaround https://github.com/rails/jquery-ujs/issues/306#issuecomment-104217519

**Comment by akbarbin** [comment]
I have fixed this with adding data options

f.submit 'Start Your Membership', :class => 'button', :data => {:disable_with => 'Please Wait...'}

Hopefully it help everyone.

**Comment by kakas** [comment]
@akbarbin ,thank you, it's very helpful
