### ISSUE TITLE
Specifiying checked and unchecked value for checkboxes

### ISSUE THREAD

**Issue by axsuul** [heartcombo/simple_form#643]
The Rails form builder allows one to specify the checked and unchecked values for checkboxes. It appears SimpleForm doesn't allow this and defaults to `1` for checked and `0` for unchecked. Is there any way to specify a checked value of `true` and unchecked value for `false` in SimpleForm? 

I need this because my attributes are within a postgresql hstore and all values are strings.

**Comment by yvzkr** [comment]
@webdevotion  thank you:)))

**Comment by schnmudgal** [comment]
Now after PR merge, it's simple as:
`f.input_field :shift_option, as: :boolean, checked_value: 'warning', unchecked_value: 'open'`
