### ISSUE TITLE
f.submit and f.button :submit don't work with raw("<tag>Value</tag>"), output markup as well

### ISSUE THREAD

**Issue by victorbstan** [heartcombo/simple_form#745]
Two examples, one not working and a working one, expected the first to follow similar pattern as the second one...

``` erb
<%= f.submit raw("<i class='icon-white icon-ok'></i> Update"), ... %>

<%= link_to raw("<i class='icon-white icon-trash'></i> Delete my account"), ... %>
```

![Screen Shot 2013-02-18 at 1 07 23 PM](https://f.cloud.github.com/assets/315297/168264/13c15522-79f6-11e2-9876-e33afaf9bdce.png)

**Comment by dantesolis** [comment]
:+1: thanks
