### ISSUE TITLE
It's not possible to have html markup in the I18n options (collection radio button and collection select)

### ISSUE THREAD

**Issue by cibernox** [heartcombo/simple_form#764]
Right now (I'm using 2.1, but I asume that master is the same since that piece of the code haven't changed) it's not possible to put html in the translation for options

The reason is in this code:

``` ruby
# lib/simple_form/inputs/collection_check_boxes_input.rb:
def build_nested_boolean_style_item_tag(collection_builder)
  collection_builder.check_box + collection_builder.text # collection_builder.text.html_safe fixes it
end
```

``` ruby
# lib/simple_form/inputs/collection_radio_buttons_input.rb:
def build_nested_boolean_style_item_tag(collection_builder)
  collection_builder.radio_button + collection_builder.text # same solution
end
```

I've changed it in a local repository, and it works. I can make a pull request, but I can't find a way o test it. That was my approach.

``` ruby
test 'input should do automatic collection translation and preserve html markup' do
  store_translations(:en, simple_form: { options: { user: {
    gender: { male: '<strong>Male</strong>', female: '<strong>Female</strong>'}
  } } } ) do
    with_input_for @user, :gender, :radio_buttons, collection: [:male, :female]
    assert_select 'input[type=radio][value=male]'
    assert_select 'input[type=radio][value=female]'
    assert_select 'label.collection_radio_buttons strong', 'Male'
    assert_select 'label.collection_radio_buttons strong', 'Female'
  end
end
```

I don't master minitest at all, I can't see what I am missing.

The commit in my fork: https://github.com/cibernox/simple_form/commit/4a0cc955848ee11e859ad2920695b6311191a0a1

**Comment by nunommc** [comment]
Hi,

I'm using version 3.2.1 and I can't get a label to use a `_html` translation.
Even after adding the gem [i18n-debug](https://github.com/fphilipe/i18n-debug) there was no lookup being made on any _html label.

In my case, it's a checkbox that I need to have a link to another url in part of the label.
Can you confirm, please?
