### ISSUE TITLE
Association in a nested form

### ISSUE THREAD

**Issue by rrivas** [heartcombo/simple_form#81]
Is it possible to create an association within a simple_fields_for object?

```
<%= simple_form_for(@rooftop) do |f| %>
 <div class="inputs">
 <%= f.input :name %>  
 <%= f.simple_fields_for "address", @address do |a| %>  
  <%= a.input :street %>  
  <%= a.association :state, :include_blank => false %>  
  <%= a.input :zip %>  
 <% end %>  
 <div class="actions">  
 <%= f.submit %>  
 </div>  
<% end %>
```

**Comment by fwolfst** [comment]
Just for the records, with rails 4 you also need to have the accept_nested_attributes_for in place.

**Comment by tboyko** [comment]
@fwolfst That's `accepts_nested_attributes_for` (with an `s` after `accept`)

**Comment by fwolfst** [comment]
@tboyko Thanks. For future readers: Never mind, I corrected the relevant message already.
