### ISSUE TITLE
Render a <button> instead an <input type=submit> for submit button?

### ISSUE THREAD

**Issue by jmuheim** [heartcombo/simple_form#814]
Hey there

I'd like to use `:after` and `:before` pseudo classes on my form buttons, and since they are only allowed for container elements (which inputs are not), I'd like to use a `<button>` tag instead of an `<input type=submit>` tag for submit buttons. Is this possible? I figured out that `f.button :submit` renders an input, not a button.

Thank you.

**Comment by sebbean** [comment]
what about the submit aspect of that?

**Comment by erindotio** [comment]
@sebbean `f.button :button, type: :submit` seems to work

**Comment by sebbean** [comment]
Hey thanks bud!

**Comment by mahemoff** [comment]
With custom label and classes:

```f.button :button, "Let's go!", type: :submit, class: :btn```

**Comment by armchairdj** [comment]
But is there anyway to override the default so that I can just use f.submit and it always does it as `f.button :button, type: :submit`?

**Comment by AlecRust** [comment]
Yes, in your form builder:

```ruby
def submit(value = nil, options = {})
  button(value, options)
end
```

But I would just use `f.button` instead of `f.submit`. `type="submit"` seems to get set automatically when `f.button` is used.
