### ISSUE TITLE
Check box collection inputs not checked on collection defined as array of symbols

### ISSUE THREAD

**Issue by mszyndel** [heartcombo/simple_form#828]
Let's say I have a following model

```
class Palette
  attr_accessible :colours
  serialize :colours, Array
end
```

and a form

```
<%= simple_form_for :palette do |f| %>
  <%= a.input :colours, collection: [:red, :green, :blue], as: :check_boxes %>
<% end %>
```

so that labels get translated automatically when rendering.
The problem I'm facing is that respective check boxes are not not checked when I am editing an object.

I've found out that a reason for that is Simple Form is not matching symbol named collection elements from field to string values retrieved from database.

Workaround for that is to alter the line like this

```
  <%= a.input :colours, collection: [:red, :green, :blue], as: :check_boxese, value_method: lambda {|v| v.last.to_s } %>
```

but this is, as you may see, quite annoying.
Is it something that you may try to fix? I think value lookup should be performed either on strings or on symbols. Changing behaviour may break some peoples implementations, so I'm not sure what is the best way to fix it.

**Comment by Thadeu** [comment]
serialize :colours, Array
Resolveu meu problema, acontece que o simple_form não aceitava Array, nem .join()

**Comment by hajder** [comment]
Hi @Thadeu thanks for your comment! Could you please edit it to be in English?

**Comment by martinverdejo** [comment]
does anyone have an elegant way disabling inline labels? for example when I'm using the checkbox inside a <td> and will use the label in another <td>.
