### ISSUE TITLE
How to customize input for postgres json type?

### ISSUE THREAD

**Issue by homanchou** [heartcombo/simple_form#860]
I have some nested data:

```
@preset = Preset.new
#fields is a postgres json data type
@preset.fields =  {'primary_category' => {'category_id' => 57882}}
```

I would like to have the same nested structure preserved in the POST `params[:preset][:fields]` from a form submit so I have this in my form partial:

```
<%= text_field_tag("preset[fields][primary_category][category_id]",nil) -%>
```

Is there a way I can extend SimpleForm to output the same existing bootstrap boilerplate that it outputs for textfields, but for my arbitrary json nested keys? 

Maybe a usage like this:

```
<%= f.input 'preset[fields][primary_category][category_id]', :as => :json_text_field %>
```

To output the same thing as helper above, but surrounded with the label, and control-group classed divs, etc.

**Comment by cgarvis** [comment]
StackOverflow question: http://stackoverflow.com/questions/18163545/how-to-customize-simple-form-for-json-nested-hash
