### ISSUE TITLE
f.error_notification on Rails 4 not showing right

### ISSUE THREAD

**Issue by Theminijohn** [heartcombo/simple_form#882]
In my Form i have

<%= simple_form_for(@album) do |f| %>
  <%= f.error_notification %>

On my older Rails Apps, the error notification worked just fine, (Red Color, healthy margins)

But with my new Rails 4 App, things don't seem to act as described.

![error](https://f.cloud.github.com/assets/2203679/1178139/24600a6c-219f-11e3-9b9b-644ee6fe9c5a.PNG)

Did i missed something, has something changed ?

**Comment by spotontheresa** [comment]
Hi, I'm using the exact same simple_form gem. Any way you fixed this?

**Comment by spotontheresa** [comment]
> Hi, I'm using the exact same simple_form gem. Any way you fixed this?

If anyone stumbles upon this question again: instead of using f.error_notifications, use f.error :base
