### ISSUE TITLE
input_field for boolean generates more than just input

### ISSUE THREAD

**Issue by mszyndel** [heartcombo/simple_form#890]
Using Rails 4.0.0 and SimpleForm 3.0.0

If in a form I use `input_field` on boolean attribute, input is wrapped in label. To my understanding it should not be.

Example code

``` erb
<%= simple_form_for @door do |f| %>
  <%= f.input_field :locked %>
<% end %>
```

generated markup would be (unimportant parts skipped)

``` html
  <form class="simple_form form-vertical">

    <input name="door[locked]" type="hidden" value="0">
    <label class="checkbox">
      <input class="boolean optional" id="door_locked" name="door[locked]" type="checkbox" value="1">
    </label>

  </form>
```

If for the same field I change field type to, let's say `:text`, only text area input is generated (as expected).

**Comment by chamnap** [comment]
I understand this is by design. However, is it possible to configure this through Wrappers API?

```ruby
b.wrapper tag: 'label', class: 'form-check-label' do |ba|
      ba.use :input, class: 'form-check-input', boolean_style: 'inline'
      ba.use :label_text
end
```
The above is not working. I'm not sure how to make it work. Any idea?
