### ISSUE TITLE
Create wrappers for "Semantic UI"

### ISSUE THREAD

**Issue by rottingcorpse** [heartcombo/simple_form#895]
https://github.com/nd0ut/semantic-ui-rails
http://http://semantic-ui.com/

**Comment by davout** [comment]
Still no plans to support `rails generate simple_form:install --semantic_ui` now that all the cool kids are using semantic ;) ?

**Comment by amingilani** [comment]
I'd like to chime in and say that this would make my life so much easier since I use semantic-ui instead of Bootstrap or Zurb in all my projects.

**Comment by pranav7** [comment]
Until this is added to as initializer to SimpleForm, you can refer to this wrapper that I have created.
https://developers.supportbee.com/blog/integrating-rails-simple-form-with-semantic-ui/

Till now, it's been working perfectly well for us.
